version: 3

tasks:
  build:
    cmds:
      - cmd: yarn tauri build --target universal-apple-darwin
        platforms: [darwin]
      - cmd: yarn tauri build
        platforms: [linux]
      - cmd: yarn tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc
        platforms: [linux]

  dev:
    cmds:
      - task: dev-release

  dev-release:
    cmds:
      - yarn tauri dev --release --features dev-release

  open: open ~/Library/Application\ Support/ai.vxb.neptune.wallet
